---

- name: keystone_data | populate data | copy data file
  copy: src=sample_data.sh dest=/tmp mode=0777
  sudo: yes
  tags: data
  
- name: keystone_data | populate data | runs the sample data
  command: "{{ item }}" 
  with_items:     
     /tmp/sample_data.sh  
  environment:
     ADMIN_PASSWORD: secret
  tags: data
  
